
### get tutor's courses
GET http://localhost:3000/courses/1


### post course
POST http://localhost:3000/courses/
Content-Type: application/json

{
    "tutor_id": 1,
    "course_name": "Fourth course",
    "posted_time": "2024-9-21T13:06:56"
}

### get course details
GET http://localhost:3000/courses/1/1




###
POST http://localhost:3000/courses/
Content-Type: application/json

{
    "tutor_id":1,
    "course_name":"This is a culinary course",
    "course_level":"Beginner"
}

###
PUT http://localhost:3000/courses/1/1
Content-Type: application/json

{
    "course_name":"This is a master culinary course",
    "course_duration":"8 hours of training",
    "course_format":"online"
}

###
DELETE http://localhost:3000/courses/1/1

### post tutor
POST http://localhost:3000/tutors/
Content-Type: application/json

{
    "tutor_name":"Jessica", 
    "tutor_pic_url":"http://tutor1.com/tutor1.pic",
    "tutor_profile": "Experienced professional"
}



### get tutors
GET http://localhost:3000/courses/1

### put
PUT http://localhost:3000/tutors/4
Content-Type: application/json

{
    "tutor_name":"James", 
    "tutor_pic_url":"http://james.com/pic",
    "tutor_profile":"Expert in thermodynamics"
}

### delete tutor
DELETE  http://localhost:3000/tutors/4


### ssr
GET http://localhost:8080/static/static-web-page.html

###
GET http://localhost:8080/tutors


### new course for tutor_id = 1
POST http://localhost:8080/courses/new/1
Content-Type: application/json

{
    "course_name":"Java web development",
    "course_description":"Teaches how to write web apps in Rust",
    "course_format":"Video",
    "course_duration":"34 hours",
    "course_price":22

}

### update course
PUT http://localhost:8080/courses/1/33
Content-Type: application/json

{
    "course_name":"Rust advanced web development",
    "course_description":"Teaches how to write advanced web apps in Rust",
    "course_format":"Video",
    "course_duration":"4 hours",
    "course_price":100

}

### delete course
DELETE http://localhost:8080/courses/delete/1/2