[package]
name = "tutor-web-app-ssr"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.9.0"
serde = { version = "1.0.210", features = ["derive"] }
tera = "1.20.0"
